### 2. 유럽국가들에 대해서는 맥주와 와인간의 상관관계는 얼마나 되는지 피어슨상관값(Pearson Correlation)을 구하기. (유럽국가들에 대해서만 맥주와 와인의 데이터를 뽑은 후에 피어슨상관값을 구하는 함수를 적용해야 함)- 02-drinks-eda.ipynb파일을 이용해야 함.

In [2]:
import pandas as pd
import numpy as np

#### drinks 데이터를 받아옴.

In [3]:
file_path = '../data/drinks.csv'
drinks = pd.read_csv(file_path)

In [16]:
drinks.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU

#### drinks 데이터 중 유럽(EU) 데이터만 가져옴.

In [38]:
europe = drinks.loc[drinks['continent']=='EU']

In [39]:
europe

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
1,Albania,89,132,54,4.9,EU
3,Andorra,245,138,312,12.4,EU
7,Armenia,21,179,11,3.8,EU
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
15,Belarus,142,373,42,14.4,EU
16,Belgium,295,84,212,10.5,EU
21,Bosnia-Herzegovina,76,173,8,4.6,EU
25,Bulgaria,231,252,94,10.3,EU
42,Croatia,230,87,254,10.2,EU
44,Cyprus,192,154,113,8.2,EU
45,Czech Republic,361,170,134,11.8,EU
48,Denmark,224,81,278,10.4,EU
57,Estonia,224,194,59,9.5,EU
60,Finland,263,133,97,10.0,EU
61,France,127,151,370,11.8,EU
64,Georgia,52,100,149,5.4,EU
65,Germany,346,117,175,11.3,EU
67,Greece,133,112,218,8.3,EU
75,Hungary,234,215,185,11.3,EU
76,Iceland,233,61,78,6.6,EU
81,Ireland,313,118,165,11.4,EU
83,Italy,85,42,237,6.5,EU
93,Latvia,281,216,62,10.5,EU
98,Lithuania,343,244,56,12.9,EU
99,Luxembourg,236,133,271,11.4,EU
105,Malta,149,100,120,6.6,EU
111,Monaco,0,0,0,0.0,EU
113,Montenegro,31,114,128,4.9,EU
120,Netherlands,251,88,190,9.4,EU
126,Norway,169,71,129,6.7,EU
135,Poland,343,215,56,10.9,EU
136,Portugal,194,67,339,11.0,EU
139,Moldova,109,226,18,6.3,EU
140,Romania,297,122,167,10.4,EU
147,San Marino,0,0,0,0.0,EU
151,Serbia,283,131,127,9.6,EU
155,Slovakia,196,293,116,11.4,EU
156,Slovenia,270,51,276,10.6,EU
160,Spain,284,157,112,10.0,EU
165,Sweden,152,60,186,7.2,EU
166,Switzerland,185,100,280,10.2,EU
170,Macedonia,106,27,86,3.9,EU
180,Ukraine,206,237,45,8.9,EU
182,United Kingdom,219,126,195,10.4,EU

#### 유럽국가들에 대한 맥주와 와인간의 피어슨상관값(Pearson Correlation)을 구함.

In [40]:
corr = europe[['beer_servings', 'wine_servings']].corr(method = 'pearson')
corr

               beer_servings  wine_servings
beer_servings       1.000000       0.297774
wine_servings       0.297774       1.000000

#### 유럽국가들에서 맥주와 와인간의 상관관계는 약 30% 로, 미약한 상관관계가 있음.